name: conductor
services:
  api:
    build:
      context: engine/
      dockerfile: src/Conductor.Engine.Api/Dockerfile
    volumes:
      - /home/james/Documents/Conductor:/tmp/conductor
    ports:
      - "8081:8080"
    develop:
      watch:
        - action: sync+restart
          path: .engine/src/Conductor.Engine.Api
          target: .engine/src/Conductor.Engine.Api
  cli:
    depends_on:
      - api
    build:
      context: client/Conductor.Client.Cli
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: .client/Conductor.Client.Cli
          target: .client/Conductor.Client.Cli
  web:
    depends_on:
      - api
    build:
      context: client/Conductor.Client.Web
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: .client/Conductor.Client.Web
          target: .client/Conductor.Client.Web