name: conductor
services:
  api:
    build:
      context: .
      dockerfile: engine/src/Conductor.Engine.Api/Dockerfile
    volumes:
      - /home/james/Documents/Conductor:/tmp/conductor
    ports:
      - "8081:8080"
    develop:
      watch:
        - action: sync+restart
          path: .engine/src/Conductor.Engine.Api
          target: .engine/src/Conductor.Engine.Api
  cli:
    env_file:
      - engine/src/Conductor.Engine.Cli/.env
    build:
      context: .
      dockerfile: engine/src/Conductor.Engine.Cli/Dockerfile
    volumes:
      - /home/james/Documents/Conductor:/tmp/conductor
    develop:
      watch:
        - action: sync+restart
          path: .engine/src/Conductor.Engine.Cli
          target: .engine/src/Conductor.Engine.Cli