name: Build & Validate
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SOLUTION_FILE: Conductor.sln

jobs:
  build-web:
    name: "Build Web"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/Conductor.Client.Web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm run format:check

      - name: Build project
        run: pnpm run build

      - name: Audit Packages
        run: pnpm audit

  build-cli:
    name: "Build Cli"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/Conductor.Client.Cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
   
      - name: Build 
        run: cargo build --release

      - name: Test
        run: cargo test

      - name: Format Check
        run: cargo fmt --check

  build-engine:
    name: "Build Engine"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        env:
          cache-name: nuget-package-cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Install Stryker.NET
        run: dotnet tool install -g dotnet-stryker

      - name: Install EF Tools
        run: dotnet tool install -g dotnet-ef --version 9.0.10

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build API
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Check No Pending Model Changes
        run: dotnet ef migrations has-pending-model-changes
        working-directory: src/Conductor.Engine.Persistence

      - name: Check For Vulnerabilities
        run: dotnet list ${{ env.SOLUTION_FILE }} package --vulnerable

      - name: Format Check
        run: dotnet format ${{ env.SOLUTION_FILE }} --verify-no-changes --verbosity diagnostic

      - uses: actions-rust-lang/setup-rust-toolchain@v1
   
      - name: Build 
        run: cargo build --release

      - name: Test
        run: cargo test
      - name: Run Tests
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Run Mutation Tests
        run: dotnet stryker --solution ${{ env.SOLUTION_FILE }}
        continue-on-error: true

  docker-compose:
    name: "Build Docker Compose"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build Docker Compose
        run: docker compose build 